spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bookingdb
    username: booking
    password: booking
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    root: INFO
