spring:
  application:
    name: booking-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/bookingdb
    username: postgres
    password: postgres
    hikari:
      schema: booking
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: booking
logging:
  level:
    root: INFO
jwt:
  private-key: classpath:jwt/app.key
  public-key: classpath:jwt/app.pub
  ttl: 15m
